CREATE TABLE INGREDIENTS(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN,
  PRIMARY KEY (ID)
);


