CREATE TABLE MEAL (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT,
  PRIMARY KEY (ID)
);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);

CREATE TABLE INGREDIENTS(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN,
  PRIMARY KEY (ID)
);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Eggs', 2.50, false, true, false, true),
('Bread', 1.90, false, true, true, false),
('Beef Patty', 4.35, false, false, false, true),
('Lettuce', 1.50, false, true, true, true),
('Yoghurt', 2.00, true, true, false, true);

SELECT *
FROM MEAL
WHERE PRICE < 15;

SELECT *
FROM INGREDIENT
WHERE VEGETARIAN;

SELECT *
FROM MEAL
WHERE CALORIES > 500;

SELECT *
FROM MEAL
WHERE PRICE >= 15 AND PRICE <= 16;

SELECT *
FROM INGREDIENT
WHERE CONTAINS_LACTOSE AND GLUTEN_FREE;

SELECT *
FROM MEAL
WHERE PRICE < 15 OR CALORIES > 600;

SELECT *
FROM INGREDIENT
WHERE VEGAN OR GLUTEN_FREE;

SELECT *
FROM MEAL
WHERE NAME = 'Pesto Pasta';

SELECT *
FROM INGREDIENT
WHERE !CONTAINS_LACTOSE;

SELECT *
FROM MEAL
WHERE PRICE > 20 AND CALORIES < 800;